"""
Repeat the characters
Create a Python function that accepts a string.
The function should return a string, with each character in the original string doubled.
If you send the function “now” as a parameter, it should return “nnooww,” and if you send “123a!”,
it should return “112233aa!!”.
"""


def repeat_characters(string):
    result = []
    for char in string:
        result.append(char)
        result.append(char)

    return ''.join(result)


# simple function generated by AI
def double_characters(text):
    return ''.join(char * 2 for char in text)


user_input = list(input('Enter a string: '))
print(repeat_characters(user_input))
print(double_characters(user_input))
